#!/bin/sh

echo Installing needed software...
sudo apt-get install curl vim-gnome curl git

echo Installing Pathogen...
mkdir -p ~/.vim/autoload ~/.vim/bundle && \
	curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim

echo Installing NERD commenter...
git clone https://github.com/scrooloose/nerdcommenter.git ~/.vim/bundle/nerdcommenter
echo Installing NERD tree...
git clone https://github.com/scrooloose/nerdtree.git ~/.vim/bundle/nerdtree
echo Installing UndoTree...
git clone https://github.com/mbbill/undotree.git ~/.vim/bundle/undotree
echo Installing Better Whitespace...
git clone git://github.com/ntpeters/vim-better-whitespace.git ~/.vim/bundle/vim-better-whitespace
echo Installing Syntastic...
git clone --depth=1 https://github.com/vim-syntastic/syntastic.git ~/.vim/bundle/syntastic
echo Installing Fugitive...
git clone git://github.com/tpope/vim-fugitive.git /home/javier/.vim/bundle/fugitive
echo Installing GitGutter...
git clone https://github.com/airblade/vim-gitgutter.git /home/javier/.vim/bundle/gitgutter
